# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "onedark"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_iseparator = "bar"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    filetree_direction = "left"
    enable_vimfiler_welcome = false
    bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after'
    project_rooter_outermost = false
    # NOTE: the value should be a list, and each item is the name of the plugin.
    # disabled_plugins = ["clighter", "clighter8"]
    default_indent = 2
    expand_tab = true



# Enable autocomplete layer
[[layers]]
    name = 'autocomplete'
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "smart"

[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30

[[layers]]
    name = "incsearch"

[[layers]]
    name = "denite"

[[layers]]
    name = 'git'

[[layers]]
    name = 'VersionControl'

[[layers]]
    name = "tmux"
    tmux_navigator_modifier = "alt"

[[layers]]
    name = "lang#vim"

[[layers]]
    name = "lang#toml"

[[layers]]
    name = "lang#sh"

[[layers]]
    name = "lang#html"

[[layers]]
    name = "lang#javascript"
    auto_fix = true
    enable_flow_syntax = true
    format_on_save = true

[[layers]]
    name = "lang#python"
    python_interpreter = "/usr/bin/python3"
    enabled_linters = ['python', 'pylint']
    format_on_save = true
    python_file_head = [
      '#!/usr/bin/env python3',
      '# -*- coding: utf-8 -*-',
      '',
      ''
    ]

[[layers]]
    name = 'lsp'
    enabled_clients = ['pylsp']

[[layers]]
    name = "lang#haskell"

[[custom_plugins]]
    repo = "joshdick/onedark.vim"
    merged = false

[[custom_plugins]]
    repo = "lilydjwg/colorizer"
    merged = false

[[custom_plugins]]
    repo = "tpope/vim-surround"
    merged = false

# [[custom_plugins]]
    # repo = "j5shi/CommandlineComplete"
    # merged = false

