preload = /home/krishnan/Pictures/Wallpapers/osman-rana-nhKKQWKK6wQ-unsplash.jpg

#set the default wallpaper(s) seen on inital workspace(s) --depending on the number of monitors used
wallpaper = eDP-1,/home/krishnan/Pictures/Wallpapers/osman-rana-nhKKQWKK6wQ-unsplash.jpg
wallpaper = HDMI-A-1,/home/krishnan/Pictures/Wallpapers/osman-rana-nhKKQWKK6wQ-unsplash.jpg
